#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Jul 09, 2020 08:08:47 AM BST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}



    menu .pop53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop53" "Popupmenu1" vTcl:WidgetProc "" 1
    menu .pop54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop54" "Popupmenu2" vTcl:WidgetProc "" 1
    menu .pop55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop55" "Popupmenu3" vTcl:WidgetProc "" 1
    menu .pop56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop56" "Popupmenu4" vTcl:WidgetProc "" 1
    menu .pop57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop57" "Popupmenu5" vTcl:WidgetProc "" 1
    menu .pop59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop59" "Popupmenu6" vTcl:WidgetProc "" 1
    menu .pop60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop60" "Popupmenu7" vTcl:WidgetProc "" 1
    menu .pop61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop61" "Popupmenu8" vTcl:WidgetProc "" 1
    menu .pop44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop44" "Popupmenu9" vTcl:WidgetProc "" 1
    menu .pop45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop45" "Popupmenu10" vTcl:WidgetProc "" 1
    menu .pop51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop51" "Popupmenu11" vTcl:WidgetProc "" 1

proc vTclWindow.top47 {base} {
    global vTcl
    if {$base == ""} {
        set base .top47
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m52" -background #d6c7c7 -highlightbackground #d8d8d8 \
        -highlightcolor black -highlightthickness 1 
    wm focusmodel $top passive
    wm geometry $top 1340x759+-168+37
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1920 1200
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "EV GUI"
    vTcl:DefineAlias "$top" "GUI" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    message $top.mes51 \
        -background #d6c7c7 \
        -font {-family {DejaVu Serif} -size 15 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ff0000 -highlightbackground #d6c7c7 \
        -highlightcolor black -highlightthickness 1 \
        -text {EV Project @ RBVH/EJV} -width 293 
    vTcl:DefineAlias "$top.mes51" "prj_name" vTcl:WidgetProc "GUI" 1
    menu $top.m52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    labelframe $top.lab60 \
        -font TkDefaultFont -foreground black -text {Data Output} \
        -background #a0d8ba -height 185 -highlightcolor black -width 630 
    vTcl:DefineAlias "$top.lab60" "Labelframe1" vTcl:WidgetProc "GUI" 1
    set site_3_0 $top.lab60
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground black -background #a0d8ba \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Speed 
    vTcl:DefineAlias "$site_3_0.lab67" "lb_VehSpd" vTcl:WidgetProc "GUI" 1
    entry $site_3_0.ent69 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 206 
    vTcl:DefineAlias "$site_3_0.ent69" "en_VehSpd" vTcl:WidgetProc "GUI" 1
    label $site_3_0.lab70 \
        -activebackground #f9f9f9 -activeforeground black -background #a0d8ba \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Torque 
    vTcl:DefineAlias "$site_3_0.lab70" "lb_Trq" vTcl:WidgetProc "GUI" 1
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black -background #a0d8ba \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Lock 
    vTcl:DefineAlias "$site_3_0.lab71" "lb_Lock" vTcl:WidgetProc "GUI" 1
    label $site_3_0.lab72 \
        -activebackground #f9f9f9 -activeforeground black -background #a0d8ba \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Accel 
    vTcl:DefineAlias "$site_3_0.lab72" "la_Acc" vTcl:WidgetProc "GUI" 1
    entry $site_3_0.ent75 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 206 
    vTcl:DefineAlias "$site_3_0.ent75" "en_Trq" vTcl:WidgetProc "GUI" 1
    entry $site_3_0.ent76 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 206 
    vTcl:DefineAlias "$site_3_0.ent76" "en_Mode" vTcl:WidgetProc "GUI" 1
    entry $site_3_0.ent77 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 206 
    vTcl:DefineAlias "$site_3_0.ent77" "en_Acc" vTcl:WidgetProc "GUI" 1
    place $site_3_0.lab67 \
        -in $site_3_0 -x 23 -y 40 -width 70 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent69 \
        -in $site_3_0 -x 94 -y 30 -width 206 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.514 -y 0 -rely 0.586 -width 0 \
        -relwidth 0.111 -height 0 -relheight 0.167 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.525 -y 0 -rely 0.204 -width 0 \
        -relwidth 0.111 -height 0 -relheight 0.167 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 25 -y 110 -width 0 -relwidth 0.111 -height 0 \
        -relheight 0.167 -anchor nw -bordermode ignore 
    place $site_3_0.ent75 \
        -in $site_3_0 -x 0 -relx 0.629 -y 0 -rely 0.538 -width 206 \
        -relwidth 0 -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent76 \
        -in $site_3_0 -x 396 -y 30 -width 206 -height 43 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent77 \
        -in $site_3_0 -x 0 -relx 0.151 -y 0 -rely 0.538 -width 206 -height 43 \
        -anchor nw -bordermode ignore 
    labelframe $top.lab65 \
        -font TkDefaultFont -foreground black -relief raised \
        -text {Control Board} -background #a3f9ff -height 445 \
        -highlightbackground #000000 -highlightcolor black -width 630 
    vTcl:DefineAlias "$top.lab65" "Labelframe1_6" vTcl:WidgetProc "GUI" 1
    set site_3_0 $top.lab65
    radiobutton $site_3_0.rad44 \
        -activebackground #93e0e5 -activeforeground black -background #a3f9ff \
        -cursor fleur \
        -font {-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #a3f9ff \
        -highlightcolor black -justify left -text ECO \
        -variable rdBtn_Mode_Eco 
    vTcl:DefineAlias "$site_3_0.rad44" "rdBtn_Mode_Eco" vTcl:WidgetProc "GUI" 1
    radiobutton $site_3_0.rad45 \
        -activebackground #93e0e5 -activeforeground black -background #a3f9ff \
        -cursor hand2 \
        -font {-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #a3f9ff \
        -highlightcolor black -justify left -text Sport \
        -variable rdBtn_Mode_Spt 
    vTcl:DefineAlias "$site_3_0.rad45" "rdBtn_Mode_Spt" vTcl:WidgetProc "GUI" 1
    radiobutton $site_3_0.rad46 \
        -activebackground #93e0e5 -activeforeground black -background #a3f9ff \
        -borderwidth 0 -cursor hand2 \
        -font {-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -height 23 \
        -highlightbackground #a3f9ff -highlightcolor black -justify left \
        -text {Mode 3} -variable rdBtn_Mode_3 -width 120 
    vTcl:DefineAlias "$site_3_0.rad46" "rdBtn_Mode_3" vTcl:WidgetProc "GUI" 1
    entry $site_3_0.ent47 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 426 
    vTcl:DefineAlias "$site_3_0.ent47" "en_SpdLim" vTcl:WidgetProc "GUI" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #a3f9ff \
        -font {-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Mode 
    vTcl:DefineAlias "$site_3_0.lab48" "lb_Mode" vTcl:WidgetProc "GUI" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #a3f9ff \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Speed Limit} 
    vTcl:DefineAlias "$site_3_0.lab49" "lb_SpdLim" vTcl:WidgetProc "GUI" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #a3f9ff \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab50" "Label1_1" vTcl:WidgetProc "GUI" 1
    scale $site_3_0.sca48 \
        -activebackground #a3f9ff -background #a3f9ff -bigincrement 0.0 \
        -cursor hand2 -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -from 0.0 -highlightbackground #a3f9ff -highlightcolor black \
        -length 100 -orient horizontal -resolution 1.0 -tickinterval 0.0 \
        -to 100.0 -troughcolor #ffffff 
    vTcl:DefineAlias "$site_3_0.sca48" "Scale1" vTcl:WidgetProc "GUI" 1
    button $site_3_0.but46 \
        -activebackground #46ff03 -activeforeground #ffffff \
        -background #46ff03 -borderwidth 5 -cursor hand2 \
        -font {-family {DejaVu Sans} -size 19 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ffffff \
        -highlightcolor #ffffff -highlightthickness 3 -overrelief groove \
        -relief groove -text UNLOCK 
    vTcl:DefineAlias "$site_3_0.but46" "btn_Unlock" vTcl:WidgetProc "GUI" 1
    button $site_3_0.but47 \
        -activebackground #f7ff0f -activeforeground #ffffff \
        -background #f7ff0f -borderwidth 5 -cursor hand2 \
        -font {-family {DejaVu Sans} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ffffff \
        -highlightcolor #ffffff -highlightthickness 3 -overrelief groove \
        -relief groove -text LOCK 
    vTcl:DefineAlias "$site_3_0.but47" "btn_Lock" vTcl:WidgetProc "GUI" 1
    button $site_3_0.but48 \
        -activebackground #ff0000 -activeforeground #ffffff \
        -background #ff0000 -borderwidth 5 -cursor hand2 \
        -font {-family {DejaVu Sans} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ffffff \
        -highlightcolor #ffffff -highlightthickness 3 -overrelief groove \
        -relief groove -text STOP 
    vTcl:DefineAlias "$site_3_0.but48" "btn_Lock_5" vTcl:WidgetProc "GUI" 1
    place $site_3_0.rad44 \
        -in $site_3_0 -x 0 -relx 0.27 -y 0 -rely 0.119 -width 0 \
        -relwidth 0.146 -height 0 -relheight 0.049 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad45 \
        -in $site_3_0 -x 0 -relx 0.48 -y 0 -rely 0.121 -width 0 \
        -relwidth 0.175 -height 0 -relheight 0.052 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad46 \
        -in $site_3_0 -x 440 -y 55 -width 120 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 0 -relx 0.256 -y 0 -rely 0.281 -width 426 \
        -relwidth 0 -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.103 -y 0 -rely 0.112 -width 0 \
        -relwidth 0.127 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.048 -y 0 -rely 0.285 -width 0 \
        -relwidth 0.191 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.102 -y 0 -rely 0.461 -width 0 \
        -relwidth 0.111 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.sca48 \
        -in $site_3_0 -x 155 -y 191 -width 444 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 0 -relx 0.079 -y 0 -rely 0.674 -width 151 \
        -relwidth 0 -height 101 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -relx 0.382 -y 0 -rely 0.674 -width 151 \
        -relwidth 0 -height 101 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -relx 0.684 -y 0 -rely 0.674 -width 151 \
        -relwidth 0 -height 101 -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab66 \
        -font TkDefaultFont -foreground black -text Graph -background #fcfcd1 \
        -height 445 -highlightcolor #ffffff -width 630 
    vTcl:DefineAlias "$top.lab66" "Labelframe1_7" vTcl:WidgetProc "GUI" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.mes51 \
        -in $top -x 0 -relx 0.119 -y 0 -rely 0.009 -width 0 -relwidth 0.219 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.513 -y 0 -rely 0.09 -width 0 -relwidth 0.47 \
        -height 0 -relheight 0.244 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.366 -width 0 -relwidth 0.47 \
        -height 0 -relheight 0.586 -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 0 -relx 0.513 -y 0 -rely 0.366 -width 0 -relwidth 0.47 \
        -height 0 -relheight 0.586 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top47 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

