#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Jul 09, 2020 01:20:54 PM BST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}



    menu .pop53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop53" "Popupmenu1" vTcl:WidgetProc "" 1
    menu .pop54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop54" "Popupmenu2" vTcl:WidgetProc "" 1
    menu .pop55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop55" "Popupmenu3" vTcl:WidgetProc "" 1
    menu .pop56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop56" "Popupmenu4" vTcl:WidgetProc "" 1
    menu .pop57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop57" "Popupmenu5" vTcl:WidgetProc "" 1
    menu .pop59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop59" "Popupmenu6" vTcl:WidgetProc "" 1
    menu .pop60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop60" "Popupmenu7" vTcl:WidgetProc "" 1
    menu .pop61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop61" "Popupmenu8" vTcl:WidgetProc "" 1
    menu .pop44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop44" "Popupmenu9" vTcl:WidgetProc "" 1
    menu .pop45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop45" "Popupmenu10" vTcl:WidgetProc "" 1
    menu .pop51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop51" "Popupmenu11" vTcl:WidgetProc "" 1

proc vTclWindow.top47 {base} {
    global vTcl
    if {$base == ""} {
        set base .top47
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m52" -background #d6c7c7 -highlightbackground #d8d8d8 \
        -highlightcolor black -highlightthickness 1 
    wm focusmodel $top passive
    wm geometry $top 1340x759+360+174
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1920 1200
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "EV GUI"
    vTcl:DefineAlias "$top" "GUI" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    message $top.mes51 \
        -background #d6c7c7 \
        -font {-family {DejaVu Serif} -size 15 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ff0000 -highlightbackground #d6c7c7 \
        -highlightcolor black -highlightthickness 1 \
        -text {EV Project @ RBVH/EJV} -width 293 
    vTcl:DefineAlias "$top.mes51" "prj_name" vTcl:WidgetProc "GUI" 1
    menu $top.m52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    labelframe $top.lab60 \
        -font TkDefaultFont -foreground black -text {Data Output} \
        -background #faffba -height 185 -highlightcolor black -width 630 
    vTcl:DefineAlias "$top.lab60" "Labelframe1" vTcl:WidgetProc "GUI" 1
    set site_3_0 $top.lab60
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground black -background #faffba \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Speed 
    vTcl:DefineAlias "$site_3_0.lab67" "lb_VehSpd" vTcl:WidgetProc "GUI" 1
    entry $site_3_0.ent69 \
        -background white -cursor {} -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 206 
    vTcl:DefineAlias "$site_3_0.ent69" "en_VehSpd" vTcl:WidgetProc "GUI" 1
    label $site_3_0.lab70 \
        -activebackground #f9f9f9 -activeforeground black -background #faffba \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Torque 
    vTcl:DefineAlias "$site_3_0.lab70" "lb_Trq" vTcl:WidgetProc "GUI" 1
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black -background #faffba \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Brake 
    vTcl:DefineAlias "$site_3_0.lab71" "lb_Brk" vTcl:WidgetProc "GUI" 1
    label $site_3_0.lab72 \
        -activebackground #f9f9f9 -activeforeground black -background #faffba \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Accel 
    vTcl:DefineAlias "$site_3_0.lab72" "la_Acc" vTcl:WidgetProc "GUI" 1
    entry $site_3_0.ent75 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 206 
    vTcl:DefineAlias "$site_3_0.ent75" "en_Trq" vTcl:WidgetProc "GUI" 1
    entry $site_3_0.ent76 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 206 
    vTcl:DefineAlias "$site_3_0.ent76" "en_Brk" vTcl:WidgetProc "GUI" 1
    entry $site_3_0.ent77 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 206 
    vTcl:DefineAlias "$site_3_0.ent77" "en_Acc" vTcl:WidgetProc "GUI" 1
    place $site_3_0.lab67 \
        -in $site_3_0 -x 23 -y 40 -width 70 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent69 \
        -in $site_3_0 -x 0 -relx 0.149 -y 0 -rely 0.171 -width 206 \
        -relwidth 0 -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.507 -y 0 -rely 0.587 -width 0 \
        -relwidth 0.111 -height 0 -relheight 0.169 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.517 -y 0 -rely 0.203 -width 0 \
        -relwidth 0.111 -height 0 -relheight 0.166 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 0 -relx 0.04 -y 0 -rely 0.588 -width 0 \
        -relwidth 0.111 -height 0 -relheight 0.171 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent75 \
        -in $site_3_0 -x 0 -relx 0.625 -y 0 -rely 0.543 -width 206 \
        -relwidth 0 -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent76 \
        -in $site_3_0 -x 0 -relx 0.623 -y 0 -rely 0.173 -width 206 \
        -relwidth 0 -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent77 \
        -in $site_3_0 -x 0 -relx 0.149 -y 0 -rely 0.541 -width 206 \
        -relwidth 0 -height 43 -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab65 \
        -font TkDefaultFont -foreground black -relief raised \
        -text {Control Board} -background #a3f9ff -height 412 \
        -highlightbackground #000000 -highlightcolor black -width 639 
    vTcl:DefineAlias "$top.lab65" "Labelframe1_6" vTcl:WidgetProc "GUI" 1
    set site_3_0 $top.lab65
    radiobutton $site_3_0.rad44 \
        -activebackground #93e0e5 -activeforeground black -background #a3f9ff \
        -cursor hand2 \
        -font {-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #a3f9ff \
        -highlightcolor black -justify left -text ECO -value MODE_ECO \
        -variable vehMode 
    vTcl:DefineAlias "$site_3_0.rad44" "rdBtn_Mode_Eco" vTcl:WidgetProc "GUI" 1
    radiobutton $site_3_0.rad45 \
        -activebackground #93e0e5 -activeforeground black -background #a3f9ff \
        -cursor hand2 \
        -font {-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #a3f9ff \
        -highlightcolor black -justify left -text Sport -value MODE_SPORT \
        -variable vehMode 
    vTcl:DefineAlias "$site_3_0.rad45" "rdBtn_Mode_Spt" vTcl:WidgetProc "GUI" 1
    radiobutton $site_3_0.rad46 \
        -activebackground #93e0e5 -activeforeground black -background #a3f9ff \
        -borderwidth 0 -cursor hand2 \
        -font {-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -height 25 \
        -highlightbackground #a3f9ff -highlightcolor black -justify left \
        -text MODE_3 -value mode3 -variable vehMode -width 142 
    vTcl:DefineAlias "$site_3_0.rad46" "rdBtn_Mode_3" vTcl:WidgetProc "GUI" 1
    entry $site_3_0.ent47 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 306 
    vTcl:DefineAlias "$site_3_0.ent47" "en_Cmd" vTcl:WidgetProc "GUI" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #a3f9ff \
        -font {-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Mode 
    vTcl:DefineAlias "$site_3_0.lab48" "lb_Mode" vTcl:WidgetProc "GUI" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #a3f9ff \
        -font {-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Command 
    vTcl:DefineAlias "$site_3_0.lab49" "lb_Cmd" vTcl:WidgetProc "GUI" 1
    button $site_3_0.but46 \
        -activebackground #46ff03 -activeforeground #ffffff \
        -background #46ff03 -borderwidth 5 -cursor hand2 \
        -font {-family {DejaVu Sans} -size 19 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ffffff \
        -highlightcolor #ffffff -highlightthickness 3 -overrelief groove \
        -relief groove -text UNLOCK 
    vTcl:DefineAlias "$site_3_0.but46" "btn_Unlock" vTcl:WidgetProc "GUI" 1
    button $site_3_0.but47 \
        -activebackground #f7ff0f -activeforeground #ffffff \
        -background #f7ff0f -borderwidth 5 -cursor hand2 \
        -font {-family {DejaVu Sans} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ffffff \
        -highlightcolor #ffffff -highlightthickness 3 -overrelief groove \
        -relief groove -text LOCK 
    vTcl:DefineAlias "$site_3_0.but47" "btn_Lock" vTcl:WidgetProc "GUI" 1
    button $site_3_0.but48 \
        -activebackground #ff0000 -activeforeground #ffffff \
        -background #ff0000 -borderwidth 5 -cursor hand2 \
        -font {-family {DejaVu Sans} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ffffff \
        -highlightcolor #ffffff -highlightthickness 3 -overrelief groove \
        -relief groove -text STOP 
    vTcl:DefineAlias "$site_3_0.but48" "btn_Lock_5" vTcl:WidgetProc "GUI" 1
    button $site_3_0.but49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -cursor fleur -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Send 
    vTcl:DefineAlias "$site_3_0.but49" "btn_SendSpdLim" vTcl:WidgetProc "GUI" 1
    entry $site_3_0.ent50 \
        -background #ffffffffffff -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 526 
    vTcl:DefineAlias "$site_3_0.ent50" "en_Console" vTcl:WidgetProc "GUI" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #a3f9ff \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Console 
    vTcl:DefineAlias "$site_3_0.lab51" "lb_Console" vTcl:WidgetProc "GUI" 1
    place $site_3_0.rad44 \
        -in $site_3_0 -x 0 -relx 0.273 -y 0 -rely 0.124 -width 0 \
        -relwidth 0.146 -height 0 -relheight 0.049 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad45 \
        -in $site_3_0 -x 0 -relx 0.455 -y 0 -rely 0.119 -width 0 \
        -relwidth 0.175 -height 0 -relheight 0.052 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad46 \
        -in $site_3_0 -x 0 -relx 0.641 -y 0 -rely 0.117 -width 0 \
        -relwidth 0.226 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 0 -relx 0.302 -y 0 -rely 0.245 -width 306 \
        -relwidth 0 -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.159 -y 0 -rely 0.115 -width 0 \
        -relwidth 0.127 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.078 -y 0 -rely 0.247 -width 0 \
        -relwidth 0.208 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 50 -y 310 -width 151 -relwidth 0 -height 101 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -relx 0.382 -y 0 -rely 0.697 -width 151 \
        -relwidth 0 -height 101 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 430 -y 309 -width 151 -relwidth 0 -height 101 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.819 -y 0 -rely 0.249 -width 73 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 0 -relx 0.079 -y 0 -rely 0.449 -width 526 \
        -relwidth 0 -height 93 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.064 -y 0 -rely 0.382 -width 0 \
        -relwidth 0.175 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab66 \
        -font TkDefaultFont -foreground black -text Graph \
        -background $vTcl(actual_gui_bg) -height 445 -highlightcolor #ffffff \
        -width 630 
    vTcl:DefineAlias "$top.lab66" "Labelframe1_7" vTcl:WidgetProc "GUI" 1
    set site_3_0 $top.lab66
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(pr,guicomplement_color)]
    ttk::notebook $site_3_0.tNo53 \
        -width 612 -height 416 -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tNo53" "TNotebook1_7" vTcl:WidgetProc "GUI" 1
    frame $site_3_0.tNo53.t0 \
        -relief groove -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo53.t0" "TNotebook1_t1_8" vTcl:WidgetProc "GUI" 1
    $site_3_0.tNo53 add $site_3_0.tNo53.t0 \
        -padding 0 -sticky nsew -state normal -text Speed -image {} \
        -compound left -underline -1 
    set site_5_0  $site_3_0.tNo53.t0
    button $site_5_0.but46 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text speed 
    vTcl:DefineAlias "$site_5_0.but46" "Button2" vTcl:WidgetProc "GUI" 1
    place $site_5_0.but46 \
        -in $site_5_0 -x 0 -relx 0.328 -y 0 -rely 0.308 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.tNo53.t1 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo53.t1" "TNotebook1_t2_9" vTcl:WidgetProc "GUI" 1
    $site_3_0.tNo53 add $site_3_0.tNo53.t1 \
        -padding 0 -sticky nsew -state normal -text Torque -image {} \
        -compound left -underline -1 
    set site_5_1  $site_3_0.tNo53.t1
    button $site_5_1.but45 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text torque 
    vTcl:DefineAlias "$site_5_1.but45" "Button1" vTcl:WidgetProc "GUI" 1
    place $site_5_1.but45 \
        -in $site_5_1 -x 0 -relx 0.41 -y 0 -rely 0.462 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tNo53 \
        -in $site_3_0 -x 0 -relx 0.016 -y 0 -rely 0.045 -width 0 \
        -relwidth 0.971 -height 0 -relheight 0.935 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab54 \
        -font TkDefaultFont -foreground black -text {Torque Formular} \
        -background $vTcl(actual_gui_bg) -height 184 -highlightcolor #ffffff \
        -width 631 
    vTcl:DefineAlias "$top.lab54" "Labelframe1_8" vTcl:WidgetProc "GUI" 1
    set site_3_0 $top.lab54
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(pr,guicomplement_color)]
    ttk::notebook $site_3_0.tNo53 \
        -width 613 -height 162 -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tNo53" "TNotebook1_8" vTcl:WidgetProc "GUI" 1
    frame $site_3_0.tNo53.t0 \
        -relief groove -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo53.t0" "TNotebook1t1_9" vTcl:WidgetProc "GUI" 1
    $site_3_0.tNo53 add $site_3_0.tNo53.t0 \
        -padding 0 -sticky nsew -state normal -text {Level 1} -image {} \
        -compound left -underline -1 
    set site_5_0  $site_3_0.tNo53.t0
    button $site_5_0.but55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Update 
    vTcl:DefineAlias "$site_5_0.but55" "btn_Update_TF" vTcl:WidgetProc "GUI" 1
    label $site_5_0.lab76 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text {Trq =} 
    vTcl:DefineAlias "$site_5_0.lab76" "Label1" vTcl:WidgetProc "GUI" 1
    label $site_5_0.lab77 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {x Trq(ACC) - } 
    vTcl:DefineAlias "$site_5_0.lab77" "Label1_15" vTcl:WidgetProc "GUI" 1
    label $site_5_0.lab78 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {x Trq(Brk) -} 
    vTcl:DefineAlias "$site_5_0.lab78" "Label1_16" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent79 \
        -background white \
        -font {-family {Liberation Mono} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 56 
    vTcl:DefineAlias "$site_5_0.ent79" "Entry1" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent80 \
        -background white \
        -font {-family {Liberation Mono} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 56 
    vTcl:DefineAlias "$site_5_0.ent80" "Entry1_17" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent81 \
        -background white \
        -font {-family {Liberation Mono} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 56 
    vTcl:DefineAlias "$site_5_0.ent81" "Entry1_18" vTcl:WidgetProc "GUI" 1
    frame $site_5_0.fra84 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 65 -highlightcolor black -width 515 
    vTcl:DefineAlias "$site_5_0.fra84" "Frame1" vTcl:WidgetProc "GUI" 1
    set site_6_0 $site_5_0.fra84
    message $site_6_0.mes87 \
        -anchor sw -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -padx 0 \
        -pady 0 \
        -text {Description: User gives the value of K1, K2 and Power-Loss Constant (C)} \
        -width 502 
    vTcl:DefineAlias "$site_6_0.mes87" "Message1" vTcl:WidgetProc "GUI" 1
    place $site_6_0.mes87 \
        -in $site_6_0 -x 0 -relx 0.008 -y 0 -rely 0.031 -width 0 \
        -relwidth 0.975 -height 0 -relheight 0.846 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but55 \
        -in $site_5_0 -x 0 -relx 0.867 -y 0 -rely 0.515 -width 67 -relwidth 0 \
        -height 41 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab76 \
        -in $site_5_0 -x 0 -relx 0.052 -y 0 -rely 0.147 -width 0 \
        -relwidth 0.115 -height 0 -relheight 0.228 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab77 \
        -in $site_5_0 -x 0 -relx 0.268 -y 0 -rely 0.147 -width 0 \
        -relwidth 0.229 -height 0 -relheight 0.228 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab78 \
        -in $site_5_0 -x 0 -relx 0.607 -y 0 -rely 0.147 -width 0 \
        -relwidth 0.229 -height 0 -relheight 0.228 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent79 \
        -in $site_5_0 -x 0 -relx 0.172 -y 0 -rely 0.147 -width 56 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent80 \
        -in $site_5_0 -x 0 -relx 0.512 -y 0 -rely 0.147 -width 56 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent81 \
        -in $site_5_0 -x 0 -relx 0.851 -y 0 -rely 0.147 -width 56 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.fra84 \
        -in $site_5_0 -x 0 -relx 0.016 -y 0 -rely 0.449 -width 0 \
        -relwidth 0.843 -height 0 -relheight 0.478 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.tNo53.t1 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo53.t1" "TNotebook1t2_10" vTcl:WidgetProc "GUI" 1
    $site_3_0.tNo53 add $site_3_0.tNo53.t1 \
        -padding 0 -sticky nsew -state normal -text {Level 2} -image {} \
        -compound left -underline -1 
    set site_5_1  $site_3_0.tNo53.t1
    frame $site_3_0.tNo53.t2 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo53.t2" "TNotebook1_8_t1" vTcl:WidgetProc "GUI" 1
    $site_3_0.tNo53 add $site_3_0.tNo53.t2 \
        -padding 0 -sticky nsew -state normal -text {Level 3} -image {} \
        -compound left -underline -1 
    set site_5_2  $site_3_0.tNo53.t2
    place $site_3_0.tNo53 \
        -in $site_3_0 -x 0 -relx 0.016 -y 0 -rely 0.109 -width 0 \
        -relwidth 0.971 -height 0 -relheight 0.88 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.mes51 \
        -in $top -x 0 -relx 0.119 -y 0 -rely 0.009 -width 0 -relwidth 0.219 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.513 -y 0 -rely 0.09 -width 0 -relwidth 0.471 \
        -height 0 -relheight 0.246 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.366 -width 0 -relwidth 0.47 \
        -height 0 -relheight 0.586 -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 0 -relx 0.513 -y 0 -rely 0.366 -width 0 -relwidth 0.47 \
        -height 0 -relheight 0.586 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.03 -y 0 -rely 0.092 -width 0 -relwidth 0.471 \
        -height 0 -relheight 0.242 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top47 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

