#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Jul 09, 2020 07:54:48 AM BST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global rdBtn_Mode_Eco
    rdBtn_Mode_Eco = tk.IntVar()
    global rdBtn_Mode_Spt
    rdBtn_Mode_Spt = tk.IntVar()
    global rdBtn_Mode_3
    rdBtn_Mode_3 = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import test_GUI
    test_GUI.vp_start_gui()




